<?php

namespace GroupeBundle\Repository;

/**
 * AlternateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlternateurRepository extends \Doctrine\ORM\EntityRepository
{
}
