<?php

namespace GroupeBundle\Repository;

/**
 * AppointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointRepository extends \Doctrine\ORM\EntityRepository
{
}
