<?php

namespace GroupeBundle\Repository;

/**
 * DeplacementGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeplacementGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
