<?php

namespace GroupeBundle\Repository;

/**
 * EmployeMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
