<?php

namespace GroupeBundle\Repository;

/**
 * GroupageHistoriqueGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupageHistoriqueGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
