<?php

namespace GroupeBundle\Repository;

use GroupeBundle\Entity\Groupe;

/**
 * HeureMarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureMarcheRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDateAndGroupe(Groupe $groupe, $dateDebut, $dateFin){

        $qb = $this->createQueryBuilder('h');

        $qb->join('h.groupe', 'g')
            ->where('g = :groupe')
            ->andWhere('h.datedebut >= :dateDebut')
            ->andWhere('h.datedebut <= :dateFin')
            ->setParameter('groupe', $groupe)
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin);

        return $qb->getQuery()
            ->getResult()
            ;


    }
}
