<?php

namespace GroupeBundle\Repository;

/**
 * HeureMarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureMarcheRepository extends \Doctrine\ORM\EntityRepository
{
}
