<?php

namespace GroupeBundle\Repository;

/**
 * HistoriqueEtatGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueEtatGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
