<?php

namespace GroupeBundle\Repository;

/**
 * HistoriqueEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueEtatRepository extends \Doctrine\ORM\EntityRepository
{
}
