<?php

namespace GroupeBundle\Repository;

/**
 * HistoriqueGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
