<?php

namespace GroupeBundle\Repository;

/**
 * HistoriqueGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
