<?php

namespace GroupeBundle\Repository;

/**
 * ListePieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListePieceRepository extends \Doctrine\ORM\EntityRepository
{
}
