<?php

namespace GroupeBundle\Repository;

/**
 * ListeEtatGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeEtatGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
