<?php

namespace GroupeBundle\Repository;

/**
 * MoteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoteurRepository extends \Doctrine\ORM\EntityRepository
{
}
