<?php

namespace GroupeBundle\Repository;

/**
 * PieceRefEqivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRefEqivRepository extends \Doctrine\ORM\EntityRepository
{
}
