<?php

namespace GroupeBundle\Repository;

/**
 * PjCatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PjCatalogueRepository extends \Doctrine\ORM\EntityRepository
{
}
