<?php

namespace GroupeBundle\Repository;

/**
 * problemePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class problemePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
