<?php

namespace GroupeBundle\Repository;

/**
 * solutionProblemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solutionProblemeRepository extends \Doctrine\ORM\EntityRepository
{
}
