<?php

namespace GroupeBundle\Repository;

/**
 * SousHeureMarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousHeureMarcheRepository extends \Doctrine\ORM\EntityRepository
{
}
