<?php

namespace GroupeBundle\Repository;

/**
 * SuiviPieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviPieceRepository extends \Doctrine\ORM\EntityRepository
{
}
