<?php

namespace ProduitBundle\Repository;

/**
 * pvsnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pvsnRepository extends \Doctrine\ORM\EntityRepository
{
}
