<?php

namespace GestionBundle\Repository;

/**
 * BonExpeditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonExpeditionRepository extends \Doctrine\ORM\EntityRepository
{
}
