<?php

namespace GestionBundle\Repository;

/**
 * BonLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
