<?php

namespace GestionBundle\Repository;

/**
 * EntreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreRepository extends \Doctrine\ORM\EntityRepository
{
}
