<?php

namespace GestionBundle\Repository;

/**
 * ligneCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
