<?php

namespace GestionBundle\Repository;

/**
 * ligneBonLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneBonLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
