<?php

namespace GestionBundle\Repository;

/**
 * ligneBonExpeditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneBonExpeditionRepository extends \Doctrine\ORM\EntityRepository
{
}
