<?php

namespace GestionBundle\Repository;

/**
 * ligneEntreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneEntreRepository extends \Doctrine\ORM\EntityRepository
{
}
