<?php

namespace GestionBundle\Repository;

/**
 * ligneCommentaireLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneCommentaireLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
