<?php

namespace GestionBundle\Repository;

/**
 * ligneSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
