<?php

namespace GestionBundle\Repository;

/**
 * ligneDeplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneDeplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
