<?php

namespace GestionBundle\Repository;

/**
 * NumDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumDocRepository extends \Doctrine\ORM\EntityRepository
{
}
