<?php

namespace GestionBundle\Repository;

/**
 * PieceJointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceJointeRepository extends \Doctrine\ORM\EntityRepository
{
}
