<?php

namespace AdminBundle\Repository;

/**
 * NombreConfirmationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NombreConfirmationRepository extends \Doctrine\ORM\EntityRepository
{
}
