<?php

namespace ClientBundle\Repository;

/**
 * FamilleClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleClientRepository extends \Doctrine\ORM\EntityRepository
{
}
