<?php

namespace ProduitBundle\Repository;

/**
 * FamilleProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
