<?php

namespace ProduitBundle\Repository;

/**
 * HistoriqueImmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueImmoRepository extends \Doctrine\ORM\EntityRepository
{
}
