<?php

namespace ProduitBundle\Repository;

/**
 * HistoriqueProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
