<?php

namespace ProduitBundle\Repository;

/**
 * HuileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HuileRepository extends \Doctrine\ORM\EntityRepository
{
}
