<?php

namespace ProduitBundle\Repository;

/**
 * ImmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmoRepository extends \Doctrine\ORM\EntityRepository
{
}
