<?php

namespace ProduitBundle\Repository;

/**
 * Stock_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Stock_Repository extends \Doctrine\ORM\EntityRepository
{
}
